Traceback (most recent call last):
  File "/Users/hamzaehsan/.vscode/extensions/ms-python.python-2019.8.30787/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/Users/hamzaehsan/.vscode/extensions/ms-python.python-2019.8.30787/pythonFiles/lib/python/ptvsd/__main__.py", line 432, in main
    run()
  File "/Users/hamzaehsan/.vscode/extensions/ms-python.python-2019.8.30787/pythonFiles/lib/python/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/Users/hamzaehsan/anaconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Users/hamzaehsan/anaconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/hamzaehsan/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/hamzaehsan/Desktop/titleTownTech/speechRecognition/main.py", line 15, in <module>
    import main as mn
  File "/Users/hamzaehsan/Desktop/titleTownTech/speechRecognition/main.py", line 69, in <module>
    start()
  File "/Users/hamzaehsan/Desktop/titleTownTech/speechRecognition/main.py", line 67, in start
    testRecord()
  File "/Users/hamzaehsan/Desktop/titleTownTech/speechRecognition/main.py", line 61, in testRecord
    predictRecording()
  File "/Users/hamzaehsan/Desktop/titleTownTech/speechRecognition/main.py", line 38, in predictRecording
    save_data_to_array(max_len=config.max_len, n_mfcc=config.buckets)
  File "/Users/hamzaehsan/Desktop/titleTownTech/speechRecognition/predictProcess.py", line 45, in save_data_to_array
    wavfiles = [path + label + '/' + wavfile for wavfile in os.listdir(path + '/' + label)]
NotADirectoryError: [Errno 20] Not a directory: './Predict//.DS_Store'
